default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lenguajes_1_development

test:
  <<: *default
  database: lenguajes_1_test

production:
  <<: *default
  database: lenguajes_1_production
  username: lenguajes_1
  password: <%= ENV["LENGUAJES_1_DATABASE_PASSWORD"] %>