Area.create(area_type: "Gasto", name: "Obra en estabulado nuevo Sota", visible: true)
Area.create(area_type: "Gasto", name: "Compra Ganado", visible: true)
Area.create(area_type: "Gasto", name: "Servicio Transporte", visible: true)
Area.create(area_type: "Gasto", name: "Compra Alimento", visible: true)
Area.create(area_type: "Gasto", name: "Comisiones compra Ganado", visible: true)
Area.create(area_type: "Gasto", name: "Compra Combustible", visible: true)
Area.create(area_type: "Gasto", name: "Compra Piña", visible: true)
Area.create(area_type: "Gasto", name: "Mantenimiento ó Reparación", visible: true)
Area.create(area_type: "Gasto", name: "Compra Repuestos", visible: true)
Area.create(area_type: "Gasto", name: "Compra Yuca", visible: true)
Area.create(area_type: "Gasto", name: "Articulos de Limpieza", visible: true)
Area.create(area_type: "Gasto", name: "Articulos de Oficina", visible: true)
Area.create(area_type: "Gasto", name: "Material P/Cerca", visible: true)
Area.create(area_type: "Gasto", name: "Medicamentos", visible: true)
Area.create(area_type: "Gasto", name: "Compra corona", visible: true)
Area.create(area_type: "Gasto", name: "Compra Boyas", visible: true)
Area.create(area_type: "Gasto", name: "Compra Refrigerios", visible: true)
Area.create(area_type: "Gasto", name: "Servicio Torno", visible: true)
Area.create(area_type: "Gasto", name: "Talonario Guías", visible: true)
Area.create(area_type: "Gasto", name: "Compra Pollinaza", visible: true)
Area.create(area_type: "Gasto", name: "Compra Mangueras y Accesorios", visible: true)
Area.create(area_type: "Gasto", name: "Rebajo Pago Anticipado", visible: true)
Area.create(area_type: "Gasto", name: "Compra Agroquimicos", visible: true)
Area.create(area_type: "Gasto", name: "Compra Sal/Miel", visible: true)
Area.create(area_type: "Gasto", name: "Ley CORFOGA", visible: true)
Area.create(area_type: "Gasto", name: "Cuenta por Pagar", visible: true)
Area.create(area_type: "Gasto", name: "Documento por Pagar", visible: true)

Area.create(area_type: "Ingreso", name: "Venta Ganado", visible: true)
Area.create(area_type: "Ingreso", name: "Intereses", visible: true)




