Area.create(area_type: "Gasto", name: "- Obra en estabulado nuevo Sota")
Area.create(area_type: "Gasto", name: "- Compra Ganado")
Area.create(area_type: "Gasto", name: "- Servicio Transporte")
Area.create(area_type: "Gasto", name: "- Compra Alimento")
Area.create(area_type: "Gasto", name: "- Comisiones compra Ganado")
Area.create(area_type: "Gasto", name: "- Compra Combustible")
Area.create(area_type: "Gasto", name: "- Compra Piña")
Area.create(area_type: "Gasto", name: "- Mantenimiento ó Reparación")
Area.create(area_type: "Gasto", name: "- Compra Repuestos")
Area.create(area_type: "Gasto", name: "- Compra Yuca")
Area.create(area_type: "Gasto", name: "- Articulos de Limpieza")
Area.create(area_type: "Gasto", name: "- Articulos de Oficina")
Area.create(area_type: "Gasto", name: "- Material P/Cerca")
Area.create(area_type: "Gasto", name: "- Medicamentos")
Area.create(area_type: "Gasto", name: "- Compra corona")
Area.create(area_type: "Gasto", name: "- Compra Boyas")
Area.create(area_type: "Gasto", name: "- Compra Refrigerios")
Area.create(area_type: "Gasto", name: "- Servicio Torno")
Area.create(area_type: "Gasto", name: "- Talonario Guías")
Area.create(area_type: "Gasto", name: "- Compra Pollinaza")
Area.create(area_type: "Gasto", name: "- Compra Mangueras y Accesorios")
Area.create(area_type: "Gasto", name: "- Rebajo Pago Anticipado")
Area.create(area_type: "Gasto", name: "- Compra Agroquimicos")
Area.create(area_type: "Gasto", name: "- Compra Sal/Miel")
Area.create(area_type: "Gasto", name: "- Ley CORFOGA")
Area.create(area_type: "Gasto", name: "- Cuenta por Pagar")
Area.create(area_type: "Gasto", name: "- Documento por Pagar")

Area.create(area_type: "Ingreso", name: "- Venta Ganado")
Area.create(area_type: "Ingreso", name: "- Intereses")




